export const services_offered_and_not_offered = [{
    "Serviços para Cachorros (oferecidos e não oferecidos)": [
      "Banho completo",
      "Tosa tradicional",
      "Tosa higiênica",
      "Hidratação de pelagem",
      "Corte de unhas",
      "Limpeza de orelhas",
      "Escovação dos dentes",
      "Passeios monitorados",
      "Adestramento básico",
      "Adestramento avançado",
      "Socialização com outros cães",
      "Acompanhamento veterinário",
      "Vacinação",
      "Castração",
      "Microchipagem",
      "Banho seco",
      "Massagem relaxante para cães",
      "Tratamento antipulgas e carrapatos",
      "Cuidados pós-operatórios",
      "Sessões de fisioterapia",
      "Hidroterapia",
      "Exercícios de reabilitação",
      "Acupuntura para cães",
      "Sessões de aromaterapia",
      "Transportes seguros para consultas",
      "Hospedagem em hotel para cães",
      "Creche para cães",
      "Sessões de agility",
      "Planejamento nutricional personalizado",
      "Entrega de rações e petiscos",
      "Sessões de enriquecimento ambiental",
      "Fotografia profissional para cães",
      "Desfile de moda canina",
      "Participação em competições de adestramento",
      "Acompanhamento para viagens (domésticas e internacionais)",
      "Treinamento para cães de terapia",
      "Treinamento para cães de guarda",
      "Treinamento para cães de serviço",
      "Atendimento domiciliar para cuidados básicos",
      "Sessões de brincadeiras controladas",
      "Consultoria comportamental",
      "Aulas para donos sobre manejo e cuidados",
      "Banho de ofurô para relaxamento",
      "Cuidados com cães idosos",
      "Assistência para cães com deficiência",
      "Acompanhamento em eventos pet-friendly",
      "Sessões de fotos temáticas",
      "Eventos de socialização em grupo",
      "Tratamentos dermatológicos",
      "Consultas nutricionais específicas",
      "Sessões de meditação e relaxamento guiado (para cães e donos)",
      "Produtos personalizados para cães",
      "Atividades interativas para estimulação mental",
      "Consultoria para preparação de adoção",
      "Sessões de treinamento virtual",
      "Programas personalizados para perda de peso",
      "Definição de limites e adaptação comportamental",
      "Sessões exclusivas para cães de luxo",
      "Atividades para fortalecimento do vínculo entre cão e dono",
      "Planos de cuidados de longo prazo"
    ]
}];
  